// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Todo struct {
	ID          int64         `json:"id"`
	Description string        `json:"description"`
	IsCompleted bool          `json:"is_completed"`
	Owner       sql.NullInt64 `json:"owner"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
}

type User struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	Password  sql.NullString `json:"password"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}
